defaults:
  - config_schema
  # dataset choice: train, test, joint (train + test)
  - dataset@experiment.training.dataset : train
  - dataset@experiment.validation.dataset: train
  - dataset@experiment.testing.dataset: test
  
  # model, algorithm & optimizer
  - optimizer@experiment.optimizer: adam
  - model@experiment.model: dqn/dqn
  - algorithm@experiment.algorithm: dqn/dqn

  # embeddings
  - embeddings/text/model@experiment.state.node_text: roberta_sentencesim
  - embeddings/text/model@experiment.state.original_user_utterance: roberta_sentencesim
  - embeddings/text/model@experiment.state.action_text: roberta_sentencesim

  - cache@experiment.cache: kapweihe

  # overwrite defaults loaded above with the following content from this file
  - _self_

experiment:
  device: cuda:0
  seed: 12345678
  cudnn_deterministic: false
  logging:
    keep_checkpoints: 5
    logging: NONE
  cache:
    active: true
  training:
    noise: 0.3
    every_steps: 1
    steps: 1000000
    dataset:
      use_answer_synonyms: true
  validation:
    noise: 0.0
    every_steps: 10000
    dialogs: 500
    dataset:
      use_answer_synonyms: true
  testing:
    noise: 0.0
    every_steps: 1000000
    dialogs: 500
    dataset:
      use_answer_synonyms: true
  # testing:
  optimizer:
    lr: 0.0001
  # model:
  #   hidden_layer_sizes: [1024, 1024]
  algorithm:
    blubb: 0.1
  environment:
    guided_free_ratio: 0.5
    auto_skip: false
    normalize_rewards: true
    max_steps: 50
    user_patience: 3
    stop_when_reaching_goal: true
    num_train_envs: 8
    num_val_envs: 8
    num_test_envs: 8
    sys_token: "[SYS]"
    usr_token: "[USR]"
    sep_token: ""
  actions:
    in_state_space: true
    action_masking: true
    stop_action: false
  state:
    # TODO: make all of these classes, so we can easily plug everything together as a sequence of maps from property -> class -> sub-vector?
    last_system_action: true
    beliefstate: true
    node_position: true
    node_type: true
    node_text:
      active: true
    original_user_utterance: 
      active: false
    dialog_history: /embeddings/text/text
    action_text:
      active: true
    action_position: true
    # TODO attentions    
    # TODO user_intent_prediction




  _target_: training.trainer.Trainer

# configuration:
#   validation:
#     active: true
#     every_train_timesteps: 10000
#     num_dialogs: 500
#     data: /data/train
#     noise: 0.0
#   testing:
#     active: true
#     every_train_timesteps: 10000
#     num_dialogs: 500
#     test: /data/test
#     noise: 0.0
