_target_: models.dqn.decoupled_dueling_dqn.DecoupledDuelingDQN
intent_prediction: true
shared_layer_sizes: [8096, 4096, 4096]
value_layer_sizes: [2048, 1024]
advantage_layer_sizes: [128]
dropout_rate: 0.25
normalization_layers: false
activation_fn: 
  _target_: torch.nn.SELU