defaults:
- dqn/targets/standard
- dqn/buffer/backend/prioritized

dqn:
  _target_: algorithm.dqn.dqn.DQNAlgorithm
  timesteps_per_reset: 1000000
  reset_exploration_times: 0
  max_grad_norm: 1.0
  batch_size: 128
  gamma: 0.99
  exploration_fraction: 0.99
  eps_start: 0.9
  eps_end: 0.0
  warmup_turns: 2560
  target_network_update_frequency: 15
  q_value_clipping: 10.0